Update ostar.yml

diff --git a/.github/workflows/ostar.yml b/.github/workflows/ostar.yml
--- a/.github/workflows/ostar.yml
+++ b/.github/workflows/ostar.yml
@@ -95,15 +95,18 @@ jobs:
         make download -j8
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: Compile the firmware
-      id: compile
-      run: |
+     - name: Compile the firmware
+       id: compile
+       run: |
         cd openwrt
-        echo "$(nproc) CPUs available, building with -j1 V=s for clear errors"
         make -j1 V=s 2>&1 | tee build.log
+        if [ ${PIPESTATUS[0]} -ne 0 ]; then
+        echo "::error::make failed"
+        exit 1
+        fi
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config \
-          | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+        | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
